### ISSUE TITLE
Search on currently shown chats

### ISSUE THREAD

**Issue by mihok** [minimalchat/mnml-operator-app#20]
Based on the current list of chats in the **Chat List** (could be All, Open, or Closed) use whats in the search input to filter those chats.

Search on Client name (in future we'll search in messages too possibly)

**Comment by teesloane** [comment]
@mihok 

How do you want message searches to be handled? Right now we are searching by the client's name, but to include a search of messages brings up a couple questions:

- what should the search order be by - match? proximity? If you are searching "sarah" will that show up if it's a client's name first or will messages have a precedence?

- another thing is, messages don't get displayed until there is an active chat. Where would messages that show up as a result of filtering go? 

- should the middle pane maybe just handle displaying clients by search, and save messages searching as a whole for another "view" entirely or perhaps from within the message pane?

Something to think about—maybe this is bigger scope than 0.1

btw bronek and I are PP right now and this came up in conversation between us .

**Comment by mihok** [comment]
Yeah these are good questions, I didnt think of the complexity involved in including searching messages in the Chat List search pane. My thoughts were, from an Operator's perspective: "I remember having a conversation about Blue elephants with a customer, who was that customer again..?" and allowing the Operator to search `Blue elephant` and have the correct chat show up.

But this may be harder to accomplish than I realized. Lets keep it to client name for 0.1

**Comment by teesloane** [comment]
Yeah, sounds good. Let's think about it. A dedicated search option might be a future feature.

ps. Add bronek's permissions ;) (see slack)

**Comment by teesloane** [comment]
This is all sorted out now (for basic search implementation--by name)
